#pragma once

#define CERF_VERSION_MAJOR 6
#define CERF_VERSION_MINOR 8
#define CERF_VERSION_PATCH 0

#define CERF_VERSION_BUILD      0

/* Windows SDK verrsrc.h VS_FIXEDFILEINFO: dwFileVersionLS packs two version
   components per DWORD ("e.g. 0x00000031 = 0.31"), so a VERSIONINFO component
   holds 16 bits and truncates past 65535. */
#define CERF_VERSION_BUILD_WORD 0
#define CERF_VERSION_DATE       ""
#define CERF_VERSION_SHA        ""

#define CERF_STR_(x)    #x
#define CERF_STR(x)     CERF_STR_(x)
#define CERF_WSTR__(x)  L##x
#define CERF_WSTR_(x)   CERF_WSTR__(x)
#define CERF_WSTR(x)    CERF_WSTR_(CERF_STR(x))

#if CERF_VERSION_PATCH
#define CERF_VERSION_STR         \
    CERF_STR(CERF_VERSION_MAJOR) "." \
    CERF_STR(CERF_VERSION_MINOR) "." \
    CERF_STR(CERF_VERSION_PATCH)
#define CERF_VERSION_WSTR         \
    CERF_WSTR(CERF_VERSION_MAJOR) L"." \
    CERF_WSTR(CERF_VERSION_MINOR) L"." \
    CERF_WSTR(CERF_VERSION_PATCH)
#else
#define CERF_VERSION_STR         \
    CERF_STR(CERF_VERSION_MAJOR) "." \
    CERF_STR(CERF_VERSION_MINOR)
#define CERF_VERSION_WSTR         \
    CERF_WSTR(CERF_VERSION_MAJOR) L"." \
    CERF_WSTR(CERF_VERSION_MINOR)
#endif

#if CERF_VERSION_BUILD
#define CERF_VERSION_BUILD_STR \
    "build " CERF_STR(CERF_VERSION_BUILD) ", " \
    CERF_VERSION_DATE ", " CERF_VERSION_SHA
#define CERF_VERSION_BUILD_WSTR \
    L"build " CERF_WSTR(CERF_VERSION_BUILD) L", " \
    CERF_WSTR_(CERF_VERSION_DATE) L", " CERF_WSTR_(CERF_VERSION_SHA)
#define CERF_VERSION_DISPLAY_STR   CERF_VERSION_STR  " ("  CERF_VERSION_BUILD_STR  ")"
#define CERF_VERSION_DISPLAY_WSTR  CERF_VERSION_WSTR L" (" CERF_VERSION_BUILD_WSTR L")"
#else
#define CERF_VERSION_BUILD_STR     ""
#define CERF_VERSION_BUILD_WSTR    L""
#define CERF_VERSION_DISPLAY_STR   CERF_VERSION_STR
#define CERF_VERSION_DISPLAY_WSTR  CERF_VERSION_WSTR
#endif
